import Instruction from "@/components/instruction/instruction";
import LandingPage from "@/components/landingpage/landingpage";
import LevelSlider from "@/components/LevelSlider/LevelSlider";

const routes = {
  home: '/',
  minimal: '/minimal',
  livePricing: '/live-pricing',
  retro: '/retro',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  createNft: '/create-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notifications',
  vote: '/vote',
  proposals: '/proposals',
  createProposal: '/proposals/create',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
  classic: '/classic',
  coinDetails: '/coin-details',
  signIn: '/authentication',
  signUp: '/authentication/sign-up',
  resetPin: '/authentication/reset-pin',
  forgetPassword: '/authentication/forget-password',
  tradingBot: '/trading-bot',
  tradingBotSpotGrid: '/spot-grid-bot',
  tradingBotFuturesGrid: '/futures-grid-bot',
  tradingBotMartingale: '/martingale-bot',
  tradingBotInfinityGrid: '/infinity-grid-bot',
  pages: '/pages',
  Non: '/non',
  Test: '/test',
  Instruction: '/instruction',
  Calculator: '/calculator',
  SmartTool: '/smarttool',
  Ideas: '/ideas',
  PromoPDFS: '/promopdfs',
  Social: '/social',
  Marathon: '/marathon',
  Links: '/links',
  Stats: '/stats',
  LandingPage: '/landingpage',
  homeminimal: '/minimal',
  Parteners: '/parteners',
  NFTS: '/nfts',
  Program: '/program',
  LevelSlider: '/levelslider',
};

export default routes;